name: Update Age Daily

on:
  schedule:
    - cron: "20 3 * * *" # run every 05:00 UTC (02:20 BrasÃ­lia)
  workflow_dispatch:

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Calculate age
        id: calc
        run: |
          CAREER_START_DATE="2018-08-13"
          TODAY=$(date +%Y-%m-%d)
          CAREER_TIME=$(($(date -d "$TODAY" +%Y) - $(date -d "$CAREER_START_DATE" +%Y)))
          if [ "$(date -d "$TODAY" +%m%d)" -lt "$(date -d "$CAREER_START_DATE" +%m%d)" ]; then CAREER_TIME=$((CAREER_TIME - 1)); fi
          echo "career_time=$CAREER_TIME" >> $GITHUB_OUTPUT

      - name: Update README
        run: |
          sed -i "s|{{CAREER_TIME}}|${{ steps.calc.outputs.career_time }}|g" README.md

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Auto-update age" || echo "No changes to commit"
          git push
